import { Metadata } from 'next'
import HeaderNew from '@/components/landing/HeaderNew'
import FooterNew from '@/components/landing/FooterNew'
import Link from 'next/link'
import { 
  CodeBracketIcon,
  DocumentTextIcon,
  ArrowPathIcon,
  CheckCircleIcon,
  ArrowRightIcon,
  CommandLineIcon,
  CubeTransparentIcon,
  CloudArrowUpIcon,
  ShieldCheckIcon,
  SparklesIcon,
  CpuChipIcon,
  DocumentDuplicateIcon,
  BoltIcon,
  BeakerIcon,
  ArrowsRightLeftIcon
} from '@heroicons/react/24/outline'

export const metadata: Metadata = {
  title: 'Automatic Infrastructure as Code | InfraUX',
  description: 'Generate Terraform, CloudFormation and Pulumi code from your visual design. Professional IaC without writing a line.',
  keywords: ['infrastructure as code', 'terraform', 'cloudformation', 'pulumi', 'iac', 'code generation'],
  openGraph: {
    title: 'Automatic IaC - InfraUX',
    description: 'From visual design to production code in seconds',
    url: 'https://infraux.com/product/iac',
    siteName: 'InfraUX',
    locale: 'en_US',
    type: 'website',
  },
}

const supportedFormats = [
  {
    name: 'Terraform',
    icon: '⚡',
    description: 'Optimized and modular HCL',
    features: ['Reusable modules', 'Parameterized variables', 'State management']
  },
  {
    name: 'CloudFormation',
    icon: '☁️',
    description: 'YAML/JSON for AWS',
    features: ['Nested stacks', 'Dynamic parameters', 'Automatic outputs']
  },
  {
    name: 'Pulumi',
    icon: '🚀',
    description: 'TypeScript, Python, Go',
    features: ['Multiple languages', 'Type-safe', 'Integrated preview']
  },
  {
    name: 'Kubernetes',
    icon: '⚓',
    description: 'YAML Manifests',
    features: ['Helm charts', 'Kustomize', 'GitOps ready']
  }
]

const codeFeatures = [
  {
    icon: DocumentTextIcon,
    title: 'Clean and Documented Code',
    description: 'Generate code following best practices with explanatory comments.',
    color: 'from-blue-500 to-cyan-500'
  },
  {
    icon: CubeTransparentIcon,
    title: 'Smart Modularization',
    description: 'Automatically organize your code into reusable modules.',
    color: 'from-purple-500 to-pink-500'
  },
  {
    icon: ArrowsRightLeftIcon,
    title: 'Bidirectional Sync',
    description: 'Import existing code and visualize it. Modify and export again.',
    color: 'from-green-500 to-emerald-500'
  },
  {
    icon: ShieldCheckIcon,
    title: 'Real-Time Validation',
    description: 'Detect syntax and configuration errors before deploying.',
    color: 'from-orange-500 to-red-500'
  },
  {
    icon: BeakerIcon,
    title: 'Integrated Testing',
    description: 'Generate automatic tests for your infrastructure.',
    color: 'from-indigo-500 to-purple-500'
  },
  {
    icon: DocumentDuplicateIcon,
    title: 'Customizable Templates',
    description: 'Create and save your own code templates.',
    color: 'from-pink-500 to-rose-500'
  }
]

const codeExample = `# Generated by InfraUX
# AWS VPC with public and private subnets

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  version = "5.0.0"

  name = "production-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["us-east-1a", "us-east-1b"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24"]

  enable_nat_gateway = true
  enable_vpn_gateway = true

  tags = {
    Environment = "production"
    ManagedBy   = "InfraUX"
  }
}`

export default function IaCPage() {
  return (
    <div className="flex flex-col min-h-screen bg-white dark:bg-black">
      <HeaderNew />
      
      <main className="flex-grow">
        {/* Hero Section - Premium Style */}
        <section className="relative py-24 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-slate-50 via-white to-emerald-50/20 dark:from-black dark:via-slate-950 dark:to-emerald-950/10" />
          <div className="absolute inset-0 bg-[url('/grid.svg')] bg-center [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]" />
          
          <div className="relative container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl">
            <div className="text-center max-w-3xl mx-auto">
              <div className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full glass-premium mb-8 animate-fade-in">
                <CodeBracketIcon className="h-5 w-5 text-emerald-500" />
                <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">
                  Infrastructure as Code
                </span>
              </div>
              
              <h1 className="text-5xl sm:text-6xl lg:text-7xl font-black text-slate-900 dark:text-white mb-6 animate-fade-in-up">
                From visual design to
                <span className="block gradient-text-emerald">
                  production code
                </span>
              </h1>
              
              <p className="text-xl lg:text-2xl text-slate-600 dark:text-slate-400 mb-8 font-medium animate-fade-in-up animation-delay-200">
                Automatically generate Terraform, CloudFormation or Pulumi code 
                from your visual design. Professional IaC without writing a line.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link
                  href="/register"
                  className="inline-flex items-center gap-3 px-10 py-5 bg-gradient-to-r from-emerald-500 to-teal-500 text-white font-bold text-lg rounded-2xl shadow-premium hover:shadow-premium-lg transform hover:scale-[1.02] transition-all duration-300 animate-fade-in-up animation-delay-300"
                >
                  <SparklesIcon className="h-6 w-6" />
                  Generate code now
                </Link>
                <Link
                  href="/demos/code-generation"
                  className="inline-flex items-center gap-3 px-10 py-5 bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-bold text-lg rounded-2xl border-2 border-slate-200 dark:border-slate-700 shadow-premium hover:shadow-premium-lg hover-lift-premium transition-all duration-300 animate-fade-in-up animation-delay-400"
                >
                  Watch demo
                  <ArrowRightIcon className="h-6 w-6" />
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* Code Example Section - Premium Style */}
        <section className="py-24 bg-gradient-to-b from-slate-50 to-white dark:from-slate-950 dark:to-black">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl">
            <div className="grid lg:grid-cols-2 gap-12 items-center">
              <div>
                <h2 className="text-4xl font-bold text-slate-900 dark:text-white mb-6">
                  Professional code, automatically generated
                </h2>
                <p className="text-xl text-slate-600 dark:text-slate-400 mb-8 font-medium">
                  InfraUX generates code following industry best practices. 
                  Modular, documented and production-ready.
                </p>
                
                <div className="space-y-4">
                  <div className="flex items-start gap-3">
                    <CheckCircleIcon className="h-6 w-6 text-emerald-600 dark:text-emerald-400 flex-shrink-0" />
                    <div>
                      <h3 className="font-semibold text-slate-900 dark:text-white">
                        Best practices included
                      </h3>
                      <p className="text-slate-600 dark:text-slate-400">
                        Naming conventions, module structure, state management
                      </p>
                    </div>
                  </div>
                  
                  <div className="flex items-start gap-3">
                    <CheckCircleIcon className="h-6 w-6 text-emerald-500 flex-shrink-0" />
                    <div>
                      <h3 className="font-bold text-lg text-slate-900 dark:text-white">
                        Smart parameterization
                      </h3>
                      <p className="text-slate-600 dark:text-slate-400">
                        Variables for environments, regions and configurations
                      </p>
                    </div>
                  </div>
                  
                  <div className="flex items-start gap-3">
                    <CheckCircleIcon className="h-6 w-6 text-emerald-600 dark:text-emerald-400 flex-shrink-0" />
                    <div>
                      <h3 className="font-semibold text-slate-900 dark:text-white">
                        Automatic documentation
                      </h3>
                      <p className="text-slate-600 dark:text-slate-400">
                        Explanatory comments and generated README
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              
              <div className="relative">
                <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/20 to-teal-500/20 blur-3xl" />
                <div className="relative bg-slate-900 rounded-3xl shadow-premium-lg overflow-hidden border border-slate-800">
                  <div className="flex items-center gap-2 px-6 py-4 bg-slate-800 border-b border-slate-700">
                    <div className="flex gap-2">
                      <div className="w-3 h-3 rounded-full bg-red-500" />
                      <div className="w-3 h-3 rounded-full bg-yellow-500" />
                      <div className="w-3 h-3 rounded-full bg-green-500" />
                    </div>
                    <span className="text-sm text-slate-400 font-mono">main.tf</span>
                  </div>
                  <pre className="p-6 text-sm overflow-x-auto">
                    <code className="text-emerald-400 font-mono">{codeExample}</code>
                  </pre>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Supported Formats - Premium Style */}
        <section className="py-24">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl">
            <div className="text-center mb-16">
              <h2 className="text-4xl sm:text-5xl font-bold text-slate-900 dark:text-white mb-6">
                Generate code in your preferred format
              </h2>
              <p className="text-xl lg:text-2xl text-slate-600 dark:text-slate-400 font-medium">
                Compatible with the most popular IaC tools
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              {supportedFormats.map((format) => (
                <div key={format.name} className="group bg-white dark:bg-slate-900 rounded-3xl p-8 shadow-premium hover:shadow-premium-lg hover-lift-premium transition-all duration-300 border border-slate-200 dark:border-slate-800">
                  <div className="text-5xl mb-6">{format.icon}</div>
                  <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-3">
                    {format.name}
                  </h3>
                  <p className="text-slate-600 dark:text-slate-400 mb-4">
                    {format.description}
                  </p>
                  <ul className="space-y-2">
                    {format.features.map((feature) => (
                      <li key={feature} className="flex items-center gap-2 text-slate-600 dark:text-slate-400">
                        <CheckCircleIcon className="h-5 w-5 text-emerald-500" />
                        {feature}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Features Grid - Premium Style */}
        <section className="py-24 bg-gradient-to-b from-slate-50 to-white dark:from-slate-950 dark:to-black">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl">
            <div className="text-center mb-16">
              <h2 className="text-4xl sm:text-5xl font-bold text-slate-900 dark:text-white mb-6">
                More than a code generator
              </h2>
              <p className="text-xl lg:text-2xl text-slate-600 dark:text-slate-400 font-medium">
                Advanced tools for professional teams
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
              {codeFeatures.map((feature, index) => {
                const Icon = feature.icon;
                return (
                  <div
                    key={feature.title}
                    className="group relative hover-lift-premium animate-fade-in-up"
                    style={{ animationDelay: `${index * 100}ms` }}
                  >
                    <div className="h-full bg-white dark:bg-slate-900 rounded-3xl p-8 border border-slate-200 dark:border-slate-800 overflow-hidden">
                      <div className="absolute inset-0 bg-gradient-to-br from-emerald-500/5 to-teal-500/5 opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                      
                      <div className="relative z-10">
                        <div className={`inline-flex p-3 bg-gradient-to-br ${feature.color} rounded-2xl shadow-lg mb-6 group-hover:scale-110 transition-transform duration-300`}>
                          <Icon className="h-8 w-8 text-white" />
                        </div>
                        <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-3">
                          {feature.title}
                        </h3>
                        <p className="text-slate-600 dark:text-slate-400">
                          {feature.description}
                        </p>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* Workflow Section - Premium Style */}
        <section className="py-24">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-7xl">
            <div className="relative">
              {/* Glow effect */}
              <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/20 to-teal-500/20 blur-3xl" />
              
              <div className="relative bg-gradient-to-r from-emerald-500 to-teal-500 rounded-3xl p-16 text-white shadow-premium-lg">
                <div className="max-w-4xl mx-auto text-center">
                  <CpuChipIcon className="h-20 w-20 mx-auto mb-8 text-white/90" />
                  <h2 className="text-4xl font-bold mb-6">
                    Complete IaC workflow
                  </h2>
                  <p className="text-xl lg:text-2xl text-emerald-50 mb-10 font-medium">
                    From design to deployment, all integrated
                  </p>
                  
                  <div className="grid md:grid-cols-3 gap-8 mb-8">
                    <div className="text-center">
                      <div className="bg-white/20 backdrop-blur-sm rounded-full w-20 h-20 flex items-center justify-center mx-auto mb-4">
                        <span className="text-3xl font-bold">1</span>
                      </div>
                      <h3 className="text-xl font-bold mb-2">Design visually</h3>
                      <p className="text-emerald-50">
                        Create your architecture with drag & drop
                      </p>
                    </div>
                    
                    <div className="text-center">
                      <div className="bg-white/20 backdrop-blur-sm rounded-full w-20 h-20 flex items-center justify-center mx-auto mb-4">
                        <span className="text-3xl font-bold">2</span>
                      </div>
                      <h3 className="text-xl font-bold mb-2">Generate code</h3>
                      <p className="text-emerald-50">
                        Export to Terraform, CloudFormation, etc.
                      </p>
                    </div>
                    
                    <div className="text-center">
                      <div className="bg-white/20 backdrop-blur-sm rounded-full w-20 h-20 flex items-center justify-center mx-auto mb-4">
                        <span className="text-3xl font-bold">3</span>
                      </div>
                      <h3 className="text-xl font-bold mb-2">Deploy</h3>
                      <p className="text-emerald-50">
                        Direct deploy or integrate with your CI/CD
                      </p>
                    </div>
                  </div>
                  
                  <div className="flex flex-col sm:flex-row gap-4 justify-center">
                    <Link
                      href="/product/deployment"
                      className="inline-flex items-center gap-3 px-10 py-5 bg-white text-emerald-600 font-bold text-lg rounded-2xl hover:bg-emerald-50 shadow-lg hover:shadow-xl transform hover:scale-[1.02] transition-all duration-300"
                    >
                      View deployment
                      <ArrowRightIcon className="h-6 w-6" />
                    </Link>
                    <Link
                      href="/product/collaboration"
                      className="inline-flex items-center gap-3 px-10 py-5 bg-emerald-600 text-white font-bold text-lg rounded-2xl hover:bg-emerald-700 shadow-lg hover:shadow-xl transform hover:scale-[1.02] transition-all duration-300"
                    >
                      View collaboration
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* CTA Section - Premium Style */}
        <section className="py-24">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl text-center">
            <h2 className="text-4xl sm:text-5xl font-bold text-slate-900 dark:text-white mb-6 animate-fade-in">
              Generate professional code in seconds
            </h2>
            <p className="text-xl lg:text-2xl text-slate-600 dark:text-slate-400 mb-10 font-medium animate-fade-in-up">
              Accelerate your infrastructure development 10x
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/register"
                className="inline-flex items-center gap-3 px-10 py-5 bg-gradient-to-r from-emerald-500 to-teal-500 text-white font-bold text-lg rounded-2xl shadow-premium hover:shadow-premium-lg transform hover:scale-[1.02] transition-all duration-300 animate-fade-in-up animation-delay-200"
              >
                Try free
                <ArrowRightIcon className="h-6 w-6" />
              </Link>
              <Link
                href="/demos/code-generation"
                className="inline-flex items-center gap-3 px-10 py-5 bg-white dark:bg-slate-900 text-slate-900 dark:text-white font-bold text-lg rounded-2xl border-2 border-slate-200 dark:border-slate-700 shadow-premium hover:shadow-premium-lg hover-lift-premium transition-all duration-300 animate-fade-in-up animation-delay-300"
              >
                View code examples
              </Link>
            </div>
          </div>
        </section>
      </main>
      
      <FooterNew />
    </div>
  )
}